---
# Define Ansible collection requirements here
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: kubernetes.core
  - name: community.okd
  - name: community.general
  - name: git+https://github.com/mlorenzofr/rhvp.cluster_utils.git,mbp-957
